### ISSUE TITLE
Missing LICENSE?

### ISSUE THREAD

**Issue by decause** [JoshData/hackathon.guide#5]
Josh,

Huge fan of your work! Thank you for all you do for the community. Srsly.

I noticed there isn't a <code>LICENSE</code> file in your repo, and wanted to clarify how contributions will be distributed if someone wanted to  help? :smile: 

Thanks!
--RemyD.

**Comment by JoshData** [comment]
Hey. Thanks.

I don't really know. I'm not particularly expecting this to become a major collaborative project.

**Comment by zachlatta** [comment]
:+1:

A good license for this might be the https://creativecommons.org/licenses/by-sa/4.0/ license. It's like the GPL, but for written content instead of code. Other people are free to use and modify the contents of this repository, but they must open source their changes under the same license.

We license most of our open source work for Hack Club (https://hackclub.io) under it (see https://github.com/hackclub/hackclub).

If you'd like, I'm happy to submit a pull request to add the license to this repo.

**Comment by JoshData** [comment]
See https://github.com/JoshData/hackathon.guide/blob/master/index.html#L485. Apparently it's been licensed the whole time.

**Comment by zachlatta** [comment]
👍

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta
